#####################################################
#      Welcome to SpyProject (The new generation)   #
#                    v1.5                           #
#                  CONTACT:                         #
#                                                   #
#        Youtube: youtube.com/c/ImNotGlitch         #
#        GitHub: github.com/ImNotGlitch             #
#                                                   #
#####################################################


# Configuração do webhook
webhook:
  AuthCommands: ""
